name: build example

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v6.0.0

      #installeert Node.Js op de github actions runner (zet enkel runtime klaar)
      - name: set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      #installeert alle dependencies uit package.json en creÃ«ert node_modules, zorgt dat tests kunnen runnen
      - name: install dependencies
        run: npm install

      - name: build code
        run: |
          zip -r app_bundle.zip . -x ".github/*"
        #zip recursief 'naam' 'alle mappen except github'

      - name: test code
        run: npm test

      - name: upload report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: junit.xml
        

  
