name: build example

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v6.0.0

      - name: set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: build code
        run: |
          zip -r app_bundle.zip . -x ".github/*" "tests/*"
        #zip recursief 'naam' 'alle mappen (.) behalve github en tests'

      - name: test code
        run: npm test
        

  
